### PR TITLE
improve performance add()

### PR DESCRIPTION
**Pull request by RobTillaart**
added some optimizations to the add() function
- only calculate new coefficients when needed
- replace one float divide by a multiply
- redid the order of testing the callback function (compare to nullptr is faster than comparing doubles)

Furthermore added a CHANGELOG.md file to inform users of changes

----

I use the Arduino build-ci for my Arduino libraries, if you want them added, let me know.

See e.g. https://github.com/RobTillaart/AS5600 => badges in the readme, so people can see the status, version etc.
It automatically builds for a number of platforms.

### CODE REVIEW

**Comment by RobTillaart** [comment]
forgot to copy the data, 
from my head the **add()** function went down from ~120 us to ~88us  so about a 25% improvement.

**Comment by RobTillaart** [comment]
Oops, my testsketch overflows, investigate

**Comment by RobTillaart** [comment]
Latest commit finally does reduce the math even more.
When the first N **add()** calls are made the time for an **add()** drops to ~44us

```
count: 7, sample: 2, average: 1, time: 88
count: 8, sample: 3, average: 1, time: 84
count: 9, sample: 4, average: 1, time: 88
count: 10, sample: 4, average: 2, time: 88
count: 11, sample: 3, average: 2, time: 40
count: 12, sample: 4, average: 2, time: 48
count: 13, sample: 3, average: 2, time: 40
count: 14, sample: 4, average: 2, time: 44
count: 15, sample: 3, average: 2, time: 40
count: 16, sample: 4, average: 2, time: 40
count: 17, sample: 4, average: 2, time: 40
count: 18, sample: 4, average: 3, time: 40
count: 19, sample: 4, average: 3, time: 40
count: 20, sample: 4, average: 3, time: 40
```

**Comment by RobTillaart** [comment]
Runtime changing the window size might fail, to be checked.

**Comment by RobTillaart** [comment]
Reduced the math to using only one coefficient.  reduced time with about 12-20 us when new coefficient is needed.
new average is calculated with an equivalent formula.

```
count: 1, sample: 0, average: 0, time: 64
count: 2, sample: 0, average: 0, time: 60
count: 1, sample: 0, average: 0, time: 64
count: 2, sample: 0, average: 0, time: 60
count: 3, sample: 1, average: 0, time: 72
count: 4, sample: 2, average: 0, time: 72
count: 5, sample: 2, average: 1, time: 76
count: 6, sample: 3, average: 1, time: 80
count: 7, sample: 2, average: 1, time: 76
count: 8, sample: 3, average: 1, time: 72
count: 9, sample: 4, average: 1, time: 72
count: 10, sample: 4, average: 2, time: 80
count: 11, sample: 3, average: 2, time: 40
count: 12, sample: 4, average: 2, time: 44
count: 13, sample: 3, average: 2, time: 44
count: 14, sample: 4, average: 2, time: 40
count: 15, sample: 3, average: 2, time: 40
count: 16, sample: 4, average: 2, time: 76
count: 17, sample: 4, average: 2, time: 40
count: 18, sample: 4, average: 2, time: 44
```

**Comment by ripred** [comment]
Great updates! Thanks!

**Pull request merged**
